CREATE TABLE authors (
    id UUID,
    full_name VARCHAR(255) NOT NULL,
    nationality VARCHAR(255) NOT NULL DEFAULT 'Unknown',
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,  

    PRIMARY KEY(id)
);